# coding=utf8
# the above tag defines encoding for this document and is for Python 2.x compatibility

import re

regex = r"""
	<blockquote(.|\n)+</blockquote>
	"""

test_str = ("<html data-lt-installed=\"true\"><head>\n"
	"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
	"  </head>\n"
	"  <body>\n"
	"    <p>Hey Amy!</p>\n"
	"    <p><br>    \n"
	"    <p>Building #39</p>\n"
	"    </p>\n"
	"    <p>I think this is your first time receiving one of these. Let me\n"
	"      know if you have any questions about how this form works. The\n"
	"      email is somewhat self-explanatory. However, reach out if you get\n"
	"      confused.</p>\n"
	"    <p>The list of information should be everything you need in order to\n"
	"      build a proposal for this group. They are answers taken directly\n"
	"      from a Google form that the director filled out.</p>\n"
	"    <p>Unfortunately, The responses aren't labeled. :( This is a\n"
	"      necessary evil with using Google forms so you may need to do a\n"
	"      little divining. 🧘‍♀️<br>\n"
	"    </p>\n"
	"    <p>ex: the bigger number is the number of students, the smaller\n"
	"      number is the number of adults etc.</p>\n"
	"    <p>You can always view the Google form itself if you need to see the\n"
	"      labels associated with the answers.<br>\n"
	"    </p>\n"
	"    <div class=\"moz-cite-prefix\">On 7/7/22 5:10 PM,\n"
	"      <a class=\"moz-txt-link-abbreviated\" href=\"mailto:***REMOVED***\">***REMOVED***</a> wrote:<br>\n"
	"    </div>\n"
	"    <blockquote type=\"cite\" cite=\"mid:CH2PR14MB4070548C8F923A519131B59FE1839@CH2PR14MB4070.namprd14.prod.outlook.com\">\n"
	"      \n"
	"      <h1>The Google Form &quot;Performance and Travel&quot; received a new\n"
	"        submission!</h1>\n"
	"      <br>\n"
	"      <p>Click here to view the <a href=\"https://docs.google.com/forms/d/1b3wDerCr7vUCwbQ3sIulGc44_wYqAVJDLgha3ifSwhA/edit\" moz-do-not-send=\"true\"><b>Google Form</b></a> this came from.</p>\n"
	"      <p>Click here to view the <a href=\"https://docs.google.com/spreadsheets/d/137HKP532tC3Y5zLl2igEenJl5IQChWVduow7Shh8ANk/edit?usp=sharing\" moz-do-not-send=\"true\">spreadsheet data.</a></p>\n"
	"      <br>\n"
	"      <br>\n"
	"      --------------------START FORM RESPONSE--------------------\n"
	"      <br>\n"
	"      <p>&nbsp;</p>\n"
	"      <style type=\"text/css\"></style>\n"
	"      <table id=\"T_eb43c_\">\n"
	"        <thead> <tr>\n"
	"            <th class=\"col_heading level0 col0\">\n"
	"              <p style=\"color: darkgreen;\">Performance and Travel Form\n"
	"                Response #39</p>\n"
	"            </th>\n"
	"          </tr>\n"
	"        </thead> <tbody>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row0_col0\" class=\"data row0 col0\"><a class=\"moz-txt-link-abbreviated\" href=\"mailto:browndj1@scsk12.org\">browndj1@scsk12.org</a></td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row1_col0\" class=\"data row1 col0\">Dallas</td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row2_col0\" class=\"data row2 col0\">30</td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row3_col0\" class=\"data row3 col0\">4</td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row4_col0\" class=\"data row4 col0\">Showcase\n"
	"              of Music</td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row5_col0\" class=\"data row5 col0\">Meals\n"
	"              Excluded</td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row6_col0\" class=\"data row6 col0\">Six Flags\n"
	"              Over Texas, Sixth Floor Museum, Cowboys Stadium Tour,\n"
	"              Dallas Galleria</td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row7_col0\" class=\"data row7 col0\">Choir</td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row8_col0\" class=\"data row8 col0\">4/6/2023</td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row9_col0\" class=\"data row9 col0\">4/9/2023</td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row10_col0\" class=\"data row10 col0\">3:00:00\n"
	"              PM</td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row11_col0\" class=\"data row11 col0\">Overton\n"
	"              High School</td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row12_col0\" class=\"data row12 col0\">Dena</td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row13_col0\" class=\"data row13 col0\">Vaughan</td>\n"
	"          </tr>\n"
	"          <tr>\n"
	"            <td id=\"T_eb43c_row14_col0\" class=\"data row14 col0\">Very\n"
	"              open to suggestions! </td>\n"
	"          </tr>\n"
	"        </tbody>\n"
	"      </table>\n"
	"      <br>\n"
	"      ----------------------END FORM RESPONSE--------------------\n"
	"      <br>\n"
	"      <br>\n"
	"      <h2>Meet Corey the Python</h2>\n"
	"      <br>\n"
	"      <img src=\"https://iili.io/jNNaDl.png\" style=\"width: 400px;\" moz-do-not-send=\"true\"><br>\n"
	"      <p>Corey is here to help you keep your tasks organized.</p>\n"
	"      <h4> If you are working on this registration update the status of\n"
	"        it by &quot;Replying to All&quot; with:</h4>\n"
	"      <ul>\n"
	"        <li>Building #39</li>\n"
	"        <li>Sent #39</li>\n"
	"        <li>Signed #39</li>\n"
	"        <li>Lost #39</li>\n"
	"        <li>Contacted #39</li>\n"
	"      </ul>\n"
	"      <p>Corey will then update the Google Sheet with the correct color.\n"
	"        You are welcome to view the <a href=\"https://docs.google.com/spreadsheets/d/137HKP532tC3Y5zLl2igEenJl5IQChWVduow7Shh8ANk/edit?usp=sharing\" moz-do-not-send=\"true\">spreadsheet</a> anytime to view your\n"
	"        overall progress with these tasks.</p>\n"
	"      <p>A few things to note about corey:</p>\n"
	"      <ul>\n"
	"        <li>Responses do not need to be case-sensitive. They do need to\n"
	"          be spelled and spaced correctly and include the '#'.</li>\n"
	"        <li>Responses do not need to be to this thread. You can email\n"
	"          Corey from any email address or CC him on any thread and he\n"
	"          will mark the correct line.</li>\n"
	"        <li>To reset the celor back to gray for &quot;Needs a Quote&quot; just\n"
	"          reply &quot;reset #39&quot;.</li>\n"
	"      </ul>\n"
	"      <br>\n"
	"      <p>Contact <a href=\"mailto:***REMOVED***\" moz-do-not-send=\"true\">Ty</a> if you have any\n"
	"        suggestions or questions.</p>\n"
	"</blockquote>\n"
	"    <div class=\"moz-signature\">-- <br>\n"
	"      <div>Ty</div>\n"
	"      <div>Director of Communications</div>\n"
	"      <div>806-712-0410</div>\n"
	"      <br>\n"
	"      <figure style=\"margin:0\"><img src=\"https://f.hubspotusercontent20.net/hubfs/3057073/000%20Approved%20Logos/Block%20Logo.png\" width=\"150\" height=\"70\"></figure>\n"
	"    </div>\n"
	"  </body>\n"
	"  <lt-container></lt-container>\n"
	"</html>")

matches = re.search(regex, test_str, re.MULTILINE | re.IGNORECASE | re.VERBOSE)

if matches:
    print ("Match was found at {start}-{end}: {match}".format(start = matches.start(), end = matches.end(), match = matches.group()))
    
    for groupNum in range(0, len(matches.groups())):
        groupNum = groupNum + 1
        
        print ("Group {groupNum} found at {start}-{end}: {group}".format(groupNum = groupNum, start = matches.start(groupNum), end = matches.end(groupNum), group = matches.group(groupNum)))

# Note: for Python 2.7 compatibility, use ur"" to prefix the regex and u"" to prefix the test string and substitution.

