name: Funneltron email checker

on:
  schedule:
    - cron: '* 11,15 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.9.12
      uses: actions/setup-python@main
      with:
        python-version: 3.9.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run email checker and labeller
      run: |
        cd code/followup; python cell_label.py
    - name: Cleanup inbox
      if: always()
      run: |
        cd code/followup; python archive_email.py
